import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/Components/Header/Header";
import { getData, getWoocommerData } from "@/utlis/getCMSData";
import api from "../config/api.json";
import Footer from "@/Components/Footer/Footer";
import AppProvider from "@/context/cartContext/AppContext";
import { Bounce, ToastContainer, toast } from "react-toastify";
import 'react-toastify/dist/ReactToastify.css';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const response = await getData(api.HeaderFooter.headerFooter);
  return (
    <html lang="en">
      <body className={inter.className}>
        <main>
          <AppProvider>
            <ToastContainer
              position="top-right"
              autoClose={5000}
              hideProgressBar={false}
              newestOnTop={false}
              closeOnClick
              rtl={false}
              pauseOnFocusLoss
              draggable
              pauseOnHover
              theme="light"
              transition={Bounce}
            />
            {/* Same as */}
            <ToastContainer />
            <Header headerData={response.data.header} />

            {children}
            <Footer footerData={response?.data} />
          </AppProvider>
        </main>
      </body>
    </html>
  );
}
